# Spring ????
spring:
  application:
    name: limou?? # ???
  output:
    ansi:
      enabled: ALWAYS # ?????????

# ?????
server:
  port: 58080

# ????
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  level:
    root: info # ??????
    com.limou.forum: debug # ????????
  file:
    path: C:/Users/Admin/Desktop/forum_log # ???????