# 项目自定义相关配置
forum:
  login:
    url: sign-in.html # 未登录状态强制跳转页面
  index: # 首页相关配置
    board-num: 9 # 首页中显示的板块个数

# 服务器配置
server:
  port: 443    #HTTPS协议默认端口号为443，需要使用其他端口时，可以在此处自定义。
  ssl:
    key-alias: tomcat    #证书别名
    key-store-password: ng7oyqqn    #填写jks-password.txt文件内的密码。
    key-store-type: JKS #JKS格式证书密钥库类型。PFX格式的证书密钥库类型为PKCS12。
    key-store: classpath:www.limou.love.jks   #您需要使用实际的证书名称替换domain_name.jks。

# Spring 全局配置
spring:
  application:
    name: 哞哞论坛 # 项目名
  output:
    ansi:
      enabled: ALWAYS # 控制台输出彩色日志
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forum_db?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 20001106
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 返回数据时JSON日期序列化格式
    default-property-inclusion: NON_NULL # 不为null时序列化
    time-zone: GMT+8 # Java中的Date默认不是东八区时间，JSON序列化时设置为东八区

# 日志配置
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  level:
    root: info # 默认日志级别
    # 开发环境
    # com.limou.forum: debug # 指定包的日志级别
  file:
    # 开发环境
    # path: C:/Users/Admin/Desktop/forum_log # 日志保存目录
    # 线上环境
    path: /opt/forum_log

# Mybatis 相关配置，这个配置是单独的，顶格写
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    # OpenAPI文档开关, true: 开启OpenAPI文档访问功能, false: 关闭
    enabled: true
    # JSON格式的OpenAPI文档的访问路径
    path: /v3/api-docs
  # 扫描哪些包来生成OpenAPI文档, 多个包名用逗号分隔
  packages-to-scan: com.limou.forum.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn